# Generated by Django 5.0.2 on 2025-03-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0004_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('hero_image', models.ImageField(upload_to='home/')),
            ],
        ),
    ]
