# Generated by Django 5.0.2 on 2025-03-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0005_aboutpage_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='about/'),
        ),
    ]
