# Generated by Django 5.0.2 on 2025-06-17 08:50

import safaris.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0010_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('lodge', 'Lodge'), ('camp', 'Camp'), ('hotel', 'Hotel')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amenities', models.TextField()),
                ('image', models.ImageField(upload_to=safaris.models.accommodation_image_path)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
