# Generated by Django 5.0.2 on 2025-06-17 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0011_accommodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='day_trips/')),
                ('type', models.CharField(choices=[('safari', 'Safari Day Trip'), ('kilimanjaro', 'Kilimanjaro Day Trip'), ('cultural', 'Cultural Day Trip'), ('adventure', 'Adventure Day Trip')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('hero_image', models.ImageField(upload_to='home/')),
            ],
        ),
        migrations.CreateModel(
            name='SafariPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='safaris/packages/')),
                ('type', models.CharField(choices=[('camping', 'Camping Safari'), ('mid_range', 'Mid-range Safari'), ('luxury', 'Luxury Safari'), ('great_migration', 'Great Migration Safari'), ('honeymoon', 'Honeymoon Safari')], default='camping', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrekkingRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mountain', models.CharField(choices=[('kilimanjaro', 'Mount Kilimanjaro'), ('meru', 'Mount Meru'), ('ol_doinyo_lengai', 'Ol Doinyo Lengai')], max_length=50)),
                ('route_name', models.CharField(blank=True, choices=[('lemosho', 'Lemosho Route'), ('marangu', 'Marangu Route'), ('machame', 'Machame Route'), ('rongai', 'Rongai Route'), ('umbwe', 'Umbwe Route')], max_length=50, null=True)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trekking/routes/')),
            ],
        ),
        migrations.AddField(
            model_name='safari',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safari',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='safari',
            name='itinerary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safari',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
