# Generated by Django 5.0.2 on 2025-06-17 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0012_daytrip_home_safaripackage_trekkingroute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('activities', models.JSONField(default=list, help_text='List of activities for the day')),
                ('meals_included', models.JSONField(default=list, help_text='List of meals included (breakfast, lunch, dinner)')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_stays', to='safaris.accommodation')),
            ],
            options={
                'ordering': ['safari', 'day_number'],
            },
        ),
        migrations.DeleteModel(
            name='DayTrip',
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='SafariPackage',
        ),
        migrations.DeleteModel(
            name='TrekkingRoute',
        ),
        migrations.AlterModelOptions(
            name='safari',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='safari',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='safari',
            name='itinerary',
        ),
        migrations.AddField(
            model_name='safari',
            name='departure_points',
            field=models.JSONField(default=list, help_text='List of departure locations with pickup times'),
        ),
        migrations.AddField(
            model_name='safari',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='safari',
            name='max_group_size',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='safari',
            name='min_age_requirement',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='safari',
            name='seasonal_availability',
            field=models.JSONField(default=dict, help_text="JSON format: {'jan': true, 'feb': true, ...}"),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='safari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='safaris.safari'),
        ),
        migrations.AlterUniqueTogether(
            name='itinerary',
            unique_together={('safari', 'day_number')},
        ),
    ]
