# Generated by Django 5.0.2 on 2025-06-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0013_itinerary_delete_daytrip_delete_home_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('special_offers', models.TextField(blank=True, null=True)),
                ('seasonal_pricing', models.JSONField(default=dict, help_text="JSON format: {'month_year': price, 'jan_2025': 1500, ...}")),
                ('group_discounts', models.JSONField(default=dict, help_text="JSON format: {'min_guests': discount_percentage, '5': 5, '10': 10}")),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('safaris', models.ManyToManyField(related_name='packages', to='safaris.safari')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
