# Generated by Django 5.0.2 on 2025-06-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0014_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_options',
            field=models.JSONField(blank=True, default=dict, help_text='Details of selected insurance policy'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_history',
            field=models.JSONField(blank=True, default=list, help_text='List of payment transaction records'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_dietary_requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
