# Generated by Django 5.0.2 on 2025-06-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0015_booking_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='User preferences for personalized recommendations (JSON format)', null=True),
        ),
    ]
