# Generated by Django 5.0.2 on 2025-07-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0020_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
