# Generated by Django 5.0.2 on 2025-07-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0024_accommodationenquiry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationenquiry',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodationenquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
