# Generated by Django 5.0.2 on 2025-07-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0027_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Deposit paid online for cash on arrival bookings.', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash_on_arrival', 'Cash on Arrival'), ('online', 'Online Payment')], default='online', help_text='How the client will pay for the safari.', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='proof_of_payment',
            field=models.FileField(blank=True, help_text='Upload proof of bank transfer payment.', null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_deposit',
            field=models.BooleanField(default=False, help_text='True if this payment is a deposit.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full'), ('deposit', 'Deposit')], default='full', help_text='Is this a full or deposit payment?', max_length=10),
        ),
    ]
